create table if not exists public.users (
    id uuid primary key references auth.users (id) on delete cascade,
    email text not null unique,
    credits integer not null default 5 check (credits >= 0),
    is_subscribed boolean not null default false,
    stripe_customer_id text unique,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.generated_images (
    id bigint generated by default as identity primary key,
    prompt text not null,
    image_url text not null,
    created_at timestamptz not null default timezone('utc', now()),
    user_id uuid not null references public.users (id) on delete cascade
);

alter table public.users enable row level security;
alter table public.generated_images enable row level security;

drop policy if exists "users_select_own" on public.users;
create policy "users_select_own"
on public.users
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "users_insert_own" on public.users;
create policy "users_insert_own"
on public.users
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "users_update_own" on public.users;
create policy "users_update_own"
on public.users
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "images_select_own" on public.generated_images;
create policy "images_select_own"
on public.generated_images
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "images_insert_own" on public.generated_images;
create policy "images_insert_own"
on public.generated_images
for insert
to authenticated
with check (auth.uid() = user_id);
